@baseURL = http://localhost:3000

POST {{baseURL}}/api/toys/comments
Content-Type: application/json

{
	"name": "Gustavo Marín",
	"email": "other@example.com",
	"comment": "Probando 123",
	"password": "abc123"
}

###

POST {{baseURL}}/api/toys/forms
Content-Type: application/json

{
	"name": "Gustavo Marín",
	"email": "other@example.com",
	"subject": "Este es un asunto",
	"content": "Este es un contenido",
	"password": "abc123forms"
}